### ISSUE TITLE
multiple issues in cordova requirements

### ISSUE THREAD

**Issue by i3games** [apache/cordova-cli#334]
`cordova requirements` has multiple issues: [Object object] output, outdated information and uncaught exceptions thrown when a requirement is not met (see screenshot).

<img width="838" alt="screen shot 2018-09-21 at 10 28 47" src="https://user-images.githubusercontent.com/830492/45873208-c5b5df00-bd89-11e8-92ab-8eb6522b3c3f.png">

MacOSX 10.12.6, Cordova 8.0.0

**Comment by raphinesse** [comment]
Thanks for reporting. Except for the CocoaPods message, this should all be fixed in the upcoming Cordova 8.1.0 release (see #333).

**Comment by i3games** [comment]
Thank, I will. I would still recommend to look into exceptions not being caught by the CLI, I just did `cordova xyz` and it throws:

```
(node:63243) UnhandledPromiseRejectionWarning: CordovaError: Cordova does not know xyz; try `cordova help` for a list of all the available commands.
    at cli (/usr/local/lib/node_modules/cordova/src/cli.js:353:15)
    at /usr/local/lib/node_modules/cordova/src/cli.js:203:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
(node:63243) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (r
ejection id: 1)
(node:63243) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

I am on node v10.4.1.
