### ISSUE TITLE
Broken on node6

### ISSUE THREAD

**Issue by janpio** [apache/cordova-cli#435]
`update-notifier` released a new version 2.6 that is automatically installed with Cordova CLI. As that dropped support for node 6, this happens:

```
E:\Projects
λ cordova -v
C:\Users\Jan\scoop\persist\nvm\nodejs\v6.16.0\node_modules\cordova\node_modules\update-notifier\index.js:74
                        (async () => {
                               ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Jan\scoop\persist\nvm\nodejs\v6.16.0\node_modules\cordova\src\cli.js:20:22)

E:\Projects
λ node -v
v6.16.0
```

**Comment by janpio** [comment]
update-notifier just pulled their release and will do a major release.
