### ISSUE TITLE
[9.0.0] Build Error 

### ISSUE THREAD

**Issue by QuasarX** [apache/cordova-cli#439]
# Bug Report

## Problem
Cordova can't build example project.

### What is expected to happen?
For a subsequent call to `cordova build android` to produce an APK.

### What does actually happen?
`cordova build android` will fail (look at Command or Code)

## Information
I'm trying to build cordova's example app. But it is give me build error.

### Command or Code
<code>cordova create hello com.example.hello HelloWorld</code>

<details><summary><code>cordova platform add android</code></summary><pre><code>
Using cordova-fetch for cordova-android@^8.0.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.example.hello
        Name: HelloWorld
        Activity: MainActivity
        Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.0.0
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Adding cordova-plugin-whitelist to package.json
</code></pre></details>

<details><summary><code>cordova build android --verbose</code></summary>

```
No scripts found for hook "before_build".
No scripts found for hook "before_prepare".
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are the same. No pkg.json modification.
Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
PlatformApi successfully found for platform android
Checking for saved plugins that haven't been added to the project
Checking for any plugins added to the project that have not been installed in android platform
No differences found between plugins added to project and installed in android platform. Continuing...
Generating platform-specific config.xml from defaults for android at C:\Users\X\Desktop\zxcv\hello\platforms\android\app\src\main\res\xml\config.xml
Merging project's config.xml into platform-specific android config.xml
[Gradle Properties] Preparing Configuration
[Gradle Properties] Appending default configuration properties
[Gradle Properties] Appending custom configuration properties
[Gradle Properties] Updating and Saving File
Merging and updating files from [www, platforms\android\platform_www] to platforms\android\app\src\main\assets\www
  copy  platforms\android\platform_www\cordova-js-src\android\nativeapiprovider.js platforms\android\app\src\main\assets\www\cordova-js-src\android\nativeapiprovider.js (updated file)
  copy  platforms\android\platform_www\cordova-js-src\android\promptbasednativeapi.js platforms\android\app\src\main\assets\www\cordova-js-src\android\promptbasednativeapi.js (updated file)
  copy  platforms\android\platform_www\cordova-js-src\exec.js platforms\android\app\src\main\assets\www\cordova-js-src\exec.js (updated file)
  copy  platforms\android\platform_www\cordova-js-src\platform.js platforms\android\app\src\main\assets\www\cordova-js-src\platform.js (updated file)
  copy  platforms\android\platform_www\cordova-js-src\plugin\android\app.js platforms\android\app\src\main\assets\www\cordova-js-src\plugin\android\app.js (updated file)
  copy  platforms\android\platform_www\cordova.js platforms\android\app\src\main\assets\www\cordova.js (updated file)
  copy  platforms\android\platform_www\cordova_plugins.js platforms\android\app\src\main\assets\www\cordova_plugins.js (updated file)
  copy  www\css\index.css platforms\android\app\src\main\assets\www\css\index.css (updated file)
  copy  www\js\index.js platforms\android\app\src\main\assets\www\js\index.js (updated file)
Wrote out android application name "HelloWorld" to C:\Users\X\Desktop\zxcv\hello\platforms\android\app\src\main\res\values\strings.xml
android-versionCode not found in config.xml. Generating a code based on version in config.xml (1.0.0): 10000
Wrote out Android package name "com.example.hello" to C:\Users\X\Desktop\zxcv\hello\platforms\android\app\src\main\java\com\example\hello\MainActivity.java
This app does not have launcher icons defined
This app does not have splash screens defined
This app does not have additional resource files defined
Prepared android project successfully
No scripts found for hook "after_prepare".
No scripts found for hook "before_compile".
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\X\AppData\Local\Android\Sdk\ (DEPRECATED)
Running command: C:\Program Files\Android\Android Studio\gradle\gradle-5.1.1\bin\gradle -p C:\Users\X\Desktop\zxcv\hello\platforms\android wrapper -b C:\Users\X\Desktop\zxcv\hello\platforms\android\wrapper.gradle

BU¦LD SUCCESSFUL in 3s
1 actionable task: 1 executed
Command finished with error code 0: C:\Program Files\Android\Android Studio\gradle\gradle-5.1.1\bin\gradle -p,C:\Users\X\Desktop\zxcv\hello\platforms\android,wrapper,-b,C:\Users\X\Desktop\zxcv\hello\platforms\android\wrapper.gradle
Subproject Path: CordovaLib
Subproject Path: app
Running command: C:\Users\X\Desktop\zxcv\hello\platforms\android\gradlew cdvBuildDebug -b C:\Users\X\Desktop\zxcv\hello\platforms\android\build.gradle

> Configure project :CordovaLib
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\X\Desktop\zxcv\hello\platforms\android\CordovaLib\build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> Failed to apply plugin [id 'com.github.dcendents.android-maven']
   > Configuration with name 'testImplementation' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 5s
Command finished with error code 1: C:\Users\X\Desktop\zxcv\hello\platforms\android\gradlew cdvBuildDebug,-b,C:\Users\X\Desktop\zxcv\hello\platforms\android\build.gradle
C:\Users\X\Desktop\zxcv\hello\platforms\android\gradlew: Command failed with exit code 1 Error output:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\X\Desktop\zxcv\hello\platforms\android\CordovaLib\build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> Failed to apply plugin [id 'com.github.dcendents.android-maven']
   > Configuration with name 'testImplementation' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 5s
Error: C:\Users\X\Desktop\zxcv\hello\platforms\android\gradlew: Command failed with exit code 1 Error output:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\X\Desktop\zxcv\hello\platforms\android\CordovaLib\build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> Failed to apply plugin [id 'com.github.dcendents.android-maven']
   > Configuration with name 'testImplementation' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 5s
    at ChildProcess.whenDone (C:\Users\X\Desktop\zxcv\hello\node_modules\cordova-common\src\superspawn.js:125:23)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.cp.emit (C:\Users\X\Desktop\zxcv\hello\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

```
</details>

### Environment, Platform, Device
Windows 10

### Version information
```
cordova -v
9.0.0 (cordova-lib@9.0.1)
node -v
v10.13.0
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
What country are you from? What locale is your OS using?

**Comment by QuasarX** [comment]
Turkey and using Turkish

**Comment by janpio** [comment]
I feared so, unfortunately nothing we can do:

> https://github.com/apache/cordova-android/issues/736#issuecomment-493776113
> This is a bug in Gradle, tracked upstream at issuetracker.google.com/issues/126874329
> I don't think there's anything Cordova can easily/realistically do to work around it 😞

See this issue: https://github.com/apache/cordova-android/issues/736

**Comment by QuasarX** [comment]
Ok, I found one solution.

https://stackoverflow.com/a/55778295
