### ISSUE TITLE
ms-adal plugin failing with corodva9

### ISSUE THREAD

**Issue by nups123** [apache/cordova-cli#457]
Hi Team,

I am build an application which works with ionic 4, xcode 10. ms-adal plugin is not working with cordova 9.
I am also using firebasex plugin also. Because of which i need cordova 9 and xcode 10.

Please give any work around for this. I want this to work with cordova 9.

Getting below error.
Adding required keychain sharing capability (ADALiOS.entitlements)..
Failed to install 'cordova-plugin-ms-adal': CordovaError: Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/Users/jenkins/.cvm/9.0.0/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at module.exports (/Users/jenkins/797ee82d/workspace/hnpsca/HNPSCA_iOS_Stage/plugins/cordova-plugin-ms-adal/scripts/configureEntitlementsIos.js:25:18)
    at runScriptViaModuleLoader (/Users/jenkins/.cvm/9.0.0/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
    at runScript (/Users/jenkins/.cvm/9.0.0/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
    at /Users/jenkins/.cvm/9.0.0/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by dpogue** [comment]
This is an error with cordova-plugin-ms-adal, not with cordova itself. Please report it to the plugin. It needs to be updated to support Cordova 9.
