### ISSUE TITLE
[ERROR] An error occurred while running subprocess cordova.

### ISSUE THREAD

**Issue by Freeman-Dogbo** [apache/cordova-cli#553]
Bonjour, voilà environ 2 semaines je ne trouve pas de solution à mon problème j'ai besoin d'aide svp

C:\Users\LENOVO\ProjetIonic>ionic cordova platform add android
> cordova.cmd platform add android
C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\windows-release\node_modules\execa\index.js:347
                throw err;
                ^

Error: Command failed: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
ou externe, un programme ex�cutable ou un fichier de commandes.

    at makeError (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\windows-release\node_modules\execa\index.js:174:9)
    at Function.module.exports.sync (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\windows-release\node_modules\execa\index.js:338:15)
    at windowsRelease (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\windows-release\index.js:39:19)
    at osName (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\os-name\index.js:39:18)
    at new Insight (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\insight\lib\index.js:37:13)
    at new RelentlessInsight (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\src\telemetry.js:31:1)
    at Object.<anonymous> (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\src\telemetry.js:39:15)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32) {
![forum d'aide](https://user-images.githubusercontent.com/76484013/113649024-38071a00-967d-11eb-8bf8-fe1cbfaa0eba.JPG)
![forum d'aide](https://user-images.githubusercontent.com/76484013/113649087-55d47f00-967d-11eb-9ddf-1315f9a13244.JPG)

  code: 1,
  stdout: '',
  stderr: "'powershell' n'est pas reconnu en tant que commande interne\r\n" +
    'ou externe, un programme ex�cutable ou un fichier de commandes.\r\n',
  failed: true,
  signal: null,
  cmd: 'powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption',
  timedOut: false
}
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd platform add android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**Comment by JCastroPalma** [comment]
stderr: "'powershell' n'est pas reconnu en tant que commande interne \ r \ n" +
buenas tardes
alguien que me ayude a resolver este problema
ese error lo arroja Ionic Repair

**Comment by mle1989972** [comment]
Hello, 
I have the same issue than Freeman-Dogbo.
![erreur cordova](https://user-images.githubusercontent.com/96699760/147890757-90907dca-7a4f-4e57-84cd-3625ceb1b7e2.jpg)

It tells me that "powershell" is not recognize in internal or external command and then the error message came.

I thing i have to edit the variable environment path for powershell but i don't know how.
![variable d'environnement](https://user-images.githubusercontent.com/96699760/147890935-0769db89-ba35-4d66-ba27-4d628969a1e6.jpg)
e environment path for powershell but i don't know how.

Do you have a clue to do that please?

Thanks for your help.

**Comment by Schahineze-lairedj** [comment]
i have this prob in system macOS 
[ERROR] An error occurred while running subprocess cordova.
        
        cordova platform add ios@latest --save exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more
        information.

**Comment by dpogue** [comment]
This sounds like this issue: https://github.com/sindresorhus/windows-release/issues/27

**Comment by dpogue** [comment]
This should be resolved by dropping the telemetry code
