### ISSUE TITLE
Create has error on WSL

### ISSUE THREAD

**Issue by nickolasnikolic** [apache/cordova-cli#618]
# Bug Report

## Problem

On WSL Ubuntu, Cordova CLI fails to create new project.

### What is expected to happen?

Creation of new project.

### What does actually happen?

cordova create helloworld
/mnt/c/Users/nick/AppData/Roaming/npm/node_modules/cordova/node_modules/hosted-git-info/lib/index.js:63
  #fill (template, opts) {
        ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/c/Users/nick/AppData/Roaming/npm/node_modules/cordova/node_modules/npm-package-arg/lib/npa.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

## Information

Environment is Windows Services for Linux Ubuntu.

### Command or Code

create

### Version information

Windows 11/Ubuntu 20

## Checklist

- [x ] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by dpogue** [comment]
What version of NodeJS are you running?

**Comment by nickolasnikolic** [comment]
***@***.***:/mnt/d/dev/web/poetry/mobile$ node -v
v12.22.9

Sent from Mail for Windows

**Comment by dpogue** [comment]
The latest version of cordova-cli (v12.0.0) require NodeJS 16.13.0 or newer.

NodeJS 12 has been end-of-life since April 2022.
