### ISSUE TITLE
SyntaxError: Unexpected token while upgrade cordova 11.0.0 to 12.0.0 on ios

### ISSUE THREAD

**Issue by Dan890** [apache/cordova-cli#623]
# Bug Report
i'm trying to update version of cordova cli from 11 to 12
but get error after updating

## Problem

![image](https://github.com/apache/cordova-cli/assets/4362735/84c0e378-e11a-4681-9b1d-5f8afdffe6ca)

### Command or Code

**sudo npm uninstall -g cordova**
removed 536 packages in 2.342s
**sudo npm i -g cordova**        
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/cordova -> /usr/local/lib/node_modules/cordova/bin/cordova
+ cordova@12.0.0
added 536 packages from 254 contributors in 26.32s
**cordova** -v                   
/usr/local/lib/node_modules/cordova/node_modules/nopt/lib/nopt-lib.js:64
  const StringType = typeDefs.String?.type
                                     ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/nopt/lib/nopt.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
sensorydev@Sensorys-Mac-mini tfilafinder % cordova platform remove ios        
/usr/local/lib/node_modules/cordova/node_modules/nopt/lib/nopt-lib.js:64
  const StringType = typeDefs.String?.type

### Environment, Platform, Device

macOS 13.3.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by hoanganhnino** [comment]
> What version of NodeJS are you running?

I've same error. My NodeJS ver is v12.16.3

**Comment by robin-huss** [comment]
This is indeed an issue when using an unsupported node version. I had the exact same issue.

Turns out i was running both nvm-windows and nodist. I configured nvm-windows to use 18.17.1, but nodist was configured with node 11.13.0. Somehow the node -v returns 18.17.1, but the actual node version used was 11.13.0. which leads to the mentioned SyntaxError.

I know this issue is closed, but i wanted to post this here to hopefully save others from having to dig into this.

**Comment by PurvaShah2020** [comment]
I am facing similar issue, can anyone help?

I tried updating node to 16.13.0

now getting below error:

There is an error in your gulpfile: 
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1

**Comment by breautek** [comment]
> I am facing similar issue, can anyone help?
> 
> I tried updating node to 16.13.0
> 
> now getting below error:
> 
> There is an error in your gulpfile: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (93) For more information on which environments are supported please see: https://github.com/sass/node-sass/releases/tag/v4.14.1

Link the information in the link says, node-sass 4.14.1 only supports up to NodeJS 14. They likely have a newer version that supports modern NodeJS runtimes.

Locking this thread because it's going off-topic of the original OP's post.
